services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: adminhost
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Rajkumar1@
      - key: WEBHOOK_URL
        value: https://your-n8n.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
